# Generated by Django 4.2.5 on 2023-10-23 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shoppers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=200, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=200, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=shoppers.models.avatar_directory_path)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
