# Generated by Django 4.2.5 on 2023-11-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.ManyToManyField(related_name='products', to='shopapp.specification', verbose_name='Характеристика'),
        ),
    ]
