# Generated by Django 4.2.5 on 2023-11-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
        ('shopapp', '0004_basket_basketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_of_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('city', models.CharField(max_length=100, verbose_name='Город доставки')),
                ('delivery_address', models.TextField(max_length=200, verbose_name='Адрес доставки')),
                ('delivery_type', models.CharField(choices=[('delivery', 'Доставка'), ('express', 'Экспресс доставка')], default='Доставка', max_length=20)),
                ('payment_type', models.CharField(choices=[('online', 'Онлайн оплата'), ('online_any', 'Онлайн оплата со случайного счета')], default='Онлайн оплата', max_length=20)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Итоговая сумма заказа')),
                ('status', models.CharField(default='inProgress', max_length=255)),
                ('payment_error', models.CharField(blank=True, default='', max_length=255)),
                ('basket', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shopapp.basket')),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myauth.profileuser', verbose_name='Покупатель')),
                ('products', models.ManyToManyField(related_name='orders', to='shopapp.product')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
