# Generated by Django 4.2.5 on 2023-11-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_product_count_of_orders_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость доставки')),
                ('delivery_express_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость экспресс доставки')),
                ('delivery_free_minimum_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Наименьшая сумма для бесплатной доставки')),
            ],
            options={
                'verbose_name': 'Постоянная доставки',
            },
        ),
    ]
